name: Node.js CI Pipeline

on:
  push:
    branches: [ "main" ] # Lắng nghe sự kiện đẩy code lên nhánh main

# THÊM KHỐI NÀY VÀO ĐỂ CẤP QUYỀN ĐẨY (PUSH) IMAGE
permissions:
  contents: read
  packages: write

jobs:
  build-va-kiem-thu:
    runs-on: ubuntu-latest # Cấp phát một máy ảo Ubuntu mới nhất

    steps:
    - name: 1. Lấy mã nguồn về máy ảo
      uses: actions/checkout@v4

    - name: 2. Cài đặt môi trường Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18' # Ứng dụng này tương thích rất tốt với Node 18

    - name: 3. Cài đặt các thư viện (Dependencies)
      run: npm install

    - name: 4. Chạy kiểm tra mã nguồn (Test)
      run: npm test

    - name: 5. Đóng gói ứng dụng thành Docker Image
      run: docker build -t my-node-app:latest .
      
    - name: 6. Kiểm tra Image đã được tạo thành công chưa
      run: docker images

    - name: 7. Quét lỗ hổng Docker Image bằng Trivy
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'my-node-app:latest' 
        format: 'table' 
        exit-code: '0' # SỬA DÒNG NÀY: Đổi từ '1' thành '0' (Chỉ báo cáo, không đánh sập)
        ignore-unfixed: true 
        vuln-type: 'os,library' 
        severity: 'CRITICAL,HIGH'

    - name: 8. Đăng nhập vào kho GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }} # Tự động lấy tên tài khoản GitHub của bạn
        password: ${{ secrets.GITHUB_TOKEN }} # Dùng chìa khóa mặc định của GitHub

    - name: 9. Gắn thẻ (Tag) và Đẩy Image lên kho
      run: |
        # Đổi tên Image cho đúng chuẩn cấu trúc của kho GitHub
        docker tag my-node-app:latest ghcr.io/${{ github.repository_owner }}/my-node-app:latest
        
        # Lệnh đẩy Image từ máy ảo lên kho
        docker push ghcr.io/${{ github.repository_owner }}/my-node-app:latest