name: Node.js CI Pipeline

on:
  push:
    branches: [ "main" ] # Lắng nghe sự kiện đẩy code lên nhánh main

jobs:
  build-va-kiem-thu:
    runs-on: ubuntu-latest # Cấp phát một máy ảo Ubuntu mới nhất

    steps:
    - name: 1. Lấy mã nguồn về máy ảo
      uses: actions/checkout@v4

    - name: 2. Cài đặt môi trường Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18' # Ứng dụng này tương thích rất tốt với Node 18

    - name: 3. Cài đặt các thư viện (Dependencies)
      run: npm install

    - name: 4. Chạy kiểm tra mã nguồn (Test)
      run: npm test

    - name: 5. Đóng gói ứng dụng thành Docker Image
      run: docker build -t my-node-app:latest .
      
    - name: 6. Kiểm tra Image đã được tạo thành công chưa
      run: docker images