name: Node.js CI Pipeline

on:
  push:
    branches: [ "main" ] # Lắng nghe sự kiện đẩy code lên nhánh main

jobs:
  build-va-kiem-thu:
    runs-on: ubuntu-latest # Cấp phát một máy ảo Ubuntu mới nhất

    steps:
    - name: 1. Lấy mã nguồn về máy ảo
      uses: actions/checkout@v4

    - name: 2. Cài đặt môi trường Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18' # Ứng dụng này tương thích rất tốt với Node 18

    - name: 3. Cài đặt các thư viện (Dependencies)
      run: npm install

    - name: 4. Chạy kiểm tra mã nguồn (Test)
      run: npm test

    - name: 5. Đóng gói ứng dụng thành Docker Image
      run: docker build -t my-node-app:latest .
      
    - name: 6. Kiểm tra Image đã được tạo thành công chưa
      run: docker images

    - name: 7. Quét lỗ hổng Docker Image bằng Trivy
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'my-node-app:latest' # Chỉ đích danh Image vừa đúc ở bước 5
        format: 'table' # Hiển thị kết quả dưới dạng bảng cho dễ nhìn
        exit-code: '1' # Đánh sập Pipeline nếu phát hiện lỗi
        ignore-unfixed: true # Bỏ qua các lỗi chưa có bản vá từ nhà phát hành
        vuln-type: 'os,library' # Quét cả hệ điều hành lẫn thư viện
        severity: 'CRITICAL,HIGH' # Chỉ báo động với các lỗi Cực kỳ nghiêm trọng và Cao